name: Publish to Winget

on:
  release:
    types: [published]

jobs:
  publish:
    # forks must not publish to the original Winget package
    if: github.repository == 'mulaRahul/keyviz'
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: mulaRahul.Keyviz
          token: ${{ secrets.WINGET_TOKEN }}